
name: PyLODE to GitHub Pages
on:
  push:
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write

jobs:
  pylode-to-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Build Pages
        uses: vliz-be-opsci/pylode-to-pages@v0
        with:
          baseuri: https://w3id.com/sal/${{ github.repository_owner }}/${{ github.event.repository.name }}
          outfolder: ./data

      - name: Convert TTL to JSON-LD
        run: |
          pip install rdflib
          python <<'EOF'
          from pathlib import Path
          from rdflib import Graph
          import os
          
          THISDIR = Path(".")
          (THISDIR / 'data').mkdir(parents=True, exist_ok=True)
          os.chown(THISDIR / 'data', os.getuid(), os.getgid())

          for ttl in THISDIR.rglob("*.ttl"):
              g = Graph()
              g.parse(ttl, format="turtle")

              jsonld = ttl.with_suffix(".jsonld")
              g.serialize(
                  destination=THISDIR.absolute() / 'data' / jsonld.name ,
                  format="json-ld",
                  indent=2,
                  auto_compact=True
              )

              print(f"{ttl} -> {jsonld}")
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
